DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
numeroMatricula INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL);

INSERT INTO ODONTOLOGOS
VALUES (DEFAULT, 123, 'CAMILO','PFIZER'),
(DEFAULT, 859, 'LUIS','PFIZER'),
(DEFAULT, 11, 'aragon','PFIZER');